### ISSUE TITLE
OpenCL Mesa

### ISSUE THREAD

**Issue by joker5bb** [genesismining/sgminer-gm#28]
Add feature to support OpenCL Mesa (Clover)

**Comment by int03h** [comment]
Not sure this is something sgminer needs to do, since OpenCL in Mesa's status is Work in Progress. Look here https://www.x.org/wiki/RadeonFeature/#Feature_Matrix_for_Free_Radeon_Drivers. In other words your choice for ATI/AMD right now are fglrx or amdgpu-pro. 

You should close this ticket until the status changes on this chart. 
[https://www.x.org/wiki/RadeonFeature/#Feature_Matrix_for_Free_Radeon_Drivers](url)

**Comment by OhGodAGirl** [comment]
As previously stated, Mesa is a work in progress, so it's not something we can do right now. Perhaps in the future. _Perhaps_. Issue is being closed until Mesa's statue is more definite.

**Comment by boredland** [comment]
Has there been any progress on both edges of this?
